//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audiogram.Modules.Trip {
    
    
    public partial class Report {
        
        /// <summary>
        /// ScriptManager9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager9;
        
        /// <summary>
        /// BasicTrip1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Audiogram.Modules.Trip.BasicTrip BasicTrip1;
        
        /// <summary>
        /// Expenses_Settlement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Audiogram.Modules.Trip.Expenses_Settlement Expenses_Settlement;
    }
}
